### PCA of the vcf files
# input datasets were kindly generated by Ryan
rm(list=ls())


library(dplyr)
library(ggplot2)
library(patchwork)
library(vegan)



# input PCA data
load("../processed_data/PCA_data/20230217_no_singletons/20240311_CT_all_eigan.Rdata")
## ct_all_eigan
load("../processed_data/PCA_data/20230217_no_singletons/20240311_CT_all_tracy.Rdata")
## ct_all_tracy





## filter the tracy results
## I checked with Ryan,
## Every fourth row of the dataframe is the tracy stat results of PCA data from 0.9 LD-pruned vcf
# So, make a index to filter these rows
index_tracy <- seq(4, nrow(ct_all_tracy), by = 4)

tracy_for_plot<-ct_all_tracy %>%
  arrange(cumsum) %>%
  slice(index_tracy)




# 
# write.table(tracy_for_plot,file = "tracy_all.txt",sep = "\t",
#             quote = FALSE,
#             row.names = FALSE)



# input geo data
indep_isotype_info_geo<-read.csv("../processed_data/Geo_info/indep_isotype_info_geo.csv")




# merge the data

index_eigan <- seq(4, nrow(ct_all_eigan), by = 4)

df_plot_all_raw <- ct_all_eigan %>% 
  slice(index_eigan)


df_plot_all <- df_plot_all_raw %>%
  dplyr::select(strain, PC1, PC2, PC3, PC4, PC5, PC6) %>%
  dplyr::rename(isotype=strain) %>%
  dplyr::left_join(., dplyr::select(indep_isotype_info_geo, isotype, geo), by='isotype')






geo.colours <- c("Hawaii"="#66C2A5", "Australia"="#FC8D62", "Central America"="#8DA0CB",
                 "South America"="#E78AC3", "Africa"="#A6D854", "Caribbean"="#FFD92F", 
                 "Taiwan" = "#E5C494")


#plot PCA





###### Plot PCA function ######

plot_PCA<-function(PCA_input, x_axis, y_axis){
  
  
  
  label_x<-tracy_for_plot %>% 
    dplyr::filter(N == x_axis) %>% 
    dplyr::select(VarExp) %>%
    pull(VarExp) %>%
    `*`(100) %>%
    round(digits = 2) %>%
    as.character()
  
  
  label_y<-tracy_for_plot %>% 
    dplyr::filter(N == y_axis) %>% 
    dplyr::select(VarExp) %>%
    pull(VarExp) %>%
    `*`(100) %>%
    round(digits = 2) %>%
    as.character()
  
  
  
p1_1<-ggplot2::ggplot(PCA_input)+
  geom_point(shape=21, alpha=0.9, size=1.5, aes(x=.data[[x_axis]],y=.data[[y_axis]], fill=geo, stroke = 0.01))+
  scale_fill_manual(values = geo.colours) +
  theme_bw() +
  labs(x=paste(x_axis," (",label_x,"%)",sep = ""),
       y=paste(y_axis," (",label_y,"%)",sep = ""))+
  theme(axis.title = element_text(size=8, face = "bold",color = "black"),
        axis.text = element_text(size=7, color = "black"),
        # legend.position='right',
        # axis.title.x=element_blank(),
        panel.grid = element_blank())
   # labs(x=x_axis, y=y_axis)  
  # scale_x_continuous(breaks = c(0, 0.1, 0.2)) +
  # guides(fill= guide_legend(nrow=2))
p1_1




p1_pc1_density <-
  ggplot2::ggplot(PCA_input)+
  geom_density(aes(x=.data[[x_axis]], group=geo,fill=geo),
               color="lightgrey", linewidth=0.01,alpha=0.6,position = 'identity',
               show.legend = F) +
  scale_fill_manual(values=geo.colours) +
  # scale_linetype_manual(values = c("solid","dashed"))+
  scale_y_discrete(expand = c(0,0.001))+
  labs(x=NULL,y=NULL)+
  theme_classic() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_line(linewidth = 0.01, color = "gray"))
p1_pc1_density



p1_pc2_density <-
  ggplot2::ggplot(PCA_input)+
  geom_density(aes(x=.data[[y_axis]], group=geo,fill=geo),
               color="lightgrey", linewidth=0.01, alpha=0.6,position = 'identity',
               show.legend = F) +
  scale_fill_manual(values=geo.colours) +
  # scale_linetype_manual(values = c("solid","dashed"))+
  scale_y_discrete(expand = c(0,0.001))+
  labs(x=NULL,y=NULL)+
  theme_classic() +
  theme(axis.text.y=element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_line(linewidth = 0.01, color = "gray"))+
  coord_flip()
p1_pc2_density



p <- p1_pc1_density + patchwork::plot_spacer() + p1_1 + p1_pc2_density +
  plot_layout(guides = 'collect', 
              widths = c(3, 1), heights = c(1,3)) & 
  theme(legend.position='none',
        plot.margin = margin(0.05, 0.15, 0.05, 0.05, unit = "cm"))
p


return(p)

}





p_PC1_PC2<- plot_PCA(PCA_input=df_plot_all,x_axis="PC1",y_axis="PC2")
p_PC1_PC2

# filter the samples in the center of the p_PC1_PC2
center_isotypes<-df_plot_all %>%
  dplyr::filter(PC1 > -0.05 & PC1 < 0.05)
nrow(center_isotypes)
# 486



p_center_isotypes<-plot_PCA(PCA_input=center_isotypes,x_axis="PC1",y_axis="PC2")
p_center_isotypes

p_PC3_PC4<- plot_PCA(PCA_input=df_plot_all,x_axis="PC3",y_axis="PC4")
p_PC3_PC4

p_PC5_PC6<- plot_PCA(PCA_input=df_plot_all,x_axis="PC5",y_axis="PC6")
p_PC5_PC6







# merge all figures
library(ggpubr)
plot_all<-ggpubr::ggarrange(p_PC1_PC2, p_PC3_PC4, p_PC5_PC6, 
                            ncol = 3, 
                            widths = c(1, 1, 1),
                            labels = c("g","h","i"))
plot_all

ggsave("../plots/PCA_plot_all.pdf", plot = plot_all, width = 7.5, height = 2.5, units = "in")







# 
# 
# ####################
# ##### Plot 3D ######
# ##### Plot 3D ######
# ##### Plot 3D ######
# ##### Plot 3D ######
# ####################
# 
# library(plotly)
# df_plot_all_3d<-df_plot_all %>%
#   dplyr::mutate(colors = geo.colours[geo])
# #
# # PC1_x<-df_plot_all_3d$PC1
# # PC2_y<-df_plot_all_3d$PC2
# # PC3_z<-df_plot_all_3d$PC3
# # PC_geo<-df_plot_all_3d$geo
# # PC_colour<-df_plot_all_3d$colors
# 
# p_3d<-plotly::plot_ly(df_plot_all_3d, x=~PC1, y=~PC2, z=~PC3,
#         type="scatter3d",
#         size= 0.2,
#         mode="markers",
#         color = ~geo,
#         colors = geo.colours)
# p_3d
# 
# library(htmlwidgets)
# htmlwidgets::saveWidget(p_3d,"PCA_3PCs.html")




